package defpackage;

import android.graphics.drawable.Drawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.InsetDrawable;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Space;
import android.widget.TextView;
import kotlin.coroutines.Continuation;
import one.me.sdk.messagewrite.recordcontrols.RecordControlsWidget;

/* renamed from: a4c  reason: default package */
public final /* synthetic */ class a4c implements u16 {
    public final /* synthetic */ int a;
    public final /* synthetic */ RecordControlsWidget b;

    public /* synthetic */ a4c(RecordControlsWidget recordControlsWidget, int i) {
        this.a = i;
        this.b = recordControlsWidget;
    }

    public final Object invoke(Object obj) {
        jue jue = jue.a;
        RecordControlsWidget recordControlsWidget = this.b;
        switch (this.a) {
            case 0:
                LinearLayout linearLayout = (LinearLayout) obj;
                k77[] k77Arr = RecordControlsWidget.m1;
                View view = new View(linearLayout.getContext());
                view.setId(y9a.h);
                float f = (float) 8;
                LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f), a24.X(f * dh4.c().getDisplayMetrics().density));
                layoutParams.setMargins(a24.X(((float) 20) * dh4.c().getDisplayMetrics().density), 0, a24.X(((float) 10) * dh4.c().getDisplayMetrics().density), 0);
                layoutParams.gravity = 16;
                view.setLayoutParams(layoutParams);
                view.setBackground((GradientDrawable) recordControlsWidget.W0.getValue());
                urd.B(new e4c(recordControlsWidget, (Continuation) null, 0), view);
                linearLayout.addView(view);
                ImageView imageView = new ImageView(linearLayout.getContext());
                imageView.setId(y9a.r);
                float f2 = (float) 36;
                LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f2), a24.X(dh4.c().getDisplayMetrics().density * f2));
                layoutParams2.gravity = 16;
                layoutParams2.leftMargin = a24.X(((float) 6) * dh4.c().getDisplayMetrics().density);
                imageView.setLayoutParams(layoutParams2);
                float f3 = (float) 4;
                me4.o(f3, dh4.c().getDisplayMetrics().density, imageView);
                imageView.setImageResource(phc.y);
                imageView.setVisibility(8);
                linearLayout.addView(imageView);
                TextView textView = new TextView(linearLayout.getContext());
                textView.setId(y9a.i);
                LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
                layoutParams3.gravity = 16;
                layoutParams3.setMarginStart(a24.X(f3 * dh4.c().getDisplayMetrics().density));
                textView.setLayoutParams(layoutParams3);
                nte.k.b(textView, yq4.b);
                urd.B(new y9(3, (Continuation) null, 21), textView);
                linearLayout.addView(textView);
                a4c a4c = new a4c(recordControlsWidget, 5);
                FrameLayout frameLayout = new FrameLayout(linearLayout.getContext());
                LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(a24.X(((float) 0) * dh4.c().getDisplayMetrics().density), -1);
                layoutParams4.weight = 1.0f;
                frameLayout.setLayoutParams(layoutParams4);
                a4c.invoke(frameLayout);
                linearLayout.addView(frameLayout);
                Space space = new Space(linearLayout.getContext());
                space.setLayoutParams(new LinearLayout.LayoutParams((int) (((float) a24.X(f2 * dh4.c().getDisplayMetrics().density)) * 1.45f), -2));
                linearLayout.addView(space);
                return jue;
            case 1:
                FrameLayout frameLayout2 = (FrameLayout) obj;
                k77[] k77Arr2 = RecordControlsWidget.m1;
                a4c a4c2 = new a4c(recordControlsWidget, 3);
                LinearLayout linearLayout2 = new LinearLayout(frameLayout2.getContext());
                linearLayout2.setId(y9a.s);
                float f4 = (float) 36;
                FrameLayout.LayoutParams layoutParams5 = new FrameLayout.LayoutParams(-1, a24.X(dh4.c().getDisplayMetrics().density * f4));
                float f5 = (float) 6;
                layoutParams5.setMargins(a24.X(dh4.c().getDisplayMetrics().density * f5), a24.X(dh4.c().getDisplayMetrics().density * f5), a24.X(dh4.c().getDisplayMetrics().density * f5), a24.X(dh4.c().getDisplayMetrics().density * f5));
                layoutParams5.gravity = 49;
                linearLayout2.setLayoutParams(layoutParams5);
                linearLayout2.setMinimumHeight(a24.X(dh4.c().getDisplayMetrics().density * f4));
                float f6 = (float) 4;
                int X = a24.X(dh4.c().getDisplayMetrics().density * f6);
                linearLayout2.setPadding(X, X, X, X);
                linearLayout2.setBackground(recordControlsWidget.M0());
                urd.B(new pf0(recordControlsWidget, (Continuation) null, 13), linearLayout2);
                a4c2.invoke(linearLayout2);
                frameLayout2.addView(linearLayout2);
                ImageView imageView2 = new ImageView(frameLayout2.getContext());
                imageView2.setId(y9a.q);
                FrameLayout.LayoutParams layoutParams6 = new FrameLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f4), a24.X(dh4.c().getDisplayMetrics().density * f4));
                layoutParams6.gravity = 8388691;
                layoutParams6.setMargins(a24.X(dh4.c().getDisplayMetrics().density * f5), 0, a24.X(dh4.c().getDisplayMetrics().density * f5), a24.X(dh4.c().getDisplayMetrics().density * f5));
                imageView2.setLayoutParams(layoutParams6);
                me4.o(f6, dh4.c().getDisplayMetrics().density, imageView2);
                imageView2.setImageResource(phc.y);
                urd.B(new ac2(3, (Continuation) null, 8), imageView2);
                a24.a0(imageView2, new c4c(recordControlsWidget, 1));
                frameLayout2.addView(imageView2);
                ImageView imageView3 = new ImageView(frameLayout2.getContext());
                imageView3.setId(y9a.m);
                FrameLayout.LayoutParams layoutParams7 = new FrameLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f4), a24.X(dh4.c().getDisplayMetrics().density * f4));
                layoutParams7.gravity = 81;
                layoutParams7.setMargins(layoutParams7.leftMargin, layoutParams7.topMargin, layoutParams7.rightMargin, a24.X(dh4.c().getDisplayMetrics().density * f5));
                imageView3.setLayoutParams(layoutParams7);
                me4.o(f6, dh4.c().getDisplayMetrics().density, imageView3);
                imageView3.setImageResource(phc.I0);
                urd.B(new ac2(3, (Continuation) null, 6), imageView3);
                a24.a0(imageView3, new c4c(recordControlsWidget, 2));
                frameLayout2.addView(imageView3);
                ImageView imageView4 = new ImageView(frameLayout2.getContext());
                imageView4.setId(y9a.o);
                FrameLayout.LayoutParams layoutParams8 = new FrameLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f4), a24.X(f4 * dh4.c().getDisplayMetrics().density));
                layoutParams8.gravity = 81;
                float f7 = (float) 0;
                layoutParams8.setMargins(a24.X(dh4.c().getDisplayMetrics().density * f7), a24.X(dh4.c().getDisplayMetrics().density * f7), a24.X(f7 * dh4.c().getDisplayMetrics().density), a24.X(f5 * dh4.c().getDisplayMetrics().density));
                imageView4.setLayoutParams(layoutParams8);
                me4.o(f6, dh4.c().getDisplayMetrics().density, imageView4);
                imageView4.setImageResource(phc.X0);
                urd.B(new ac2(3, (Continuation) null, 7), imageView4);
                imageView4.setVisibility(8);
                a24.a0(imageView4, new c4c(recordControlsWidget, 0));
                frameLayout2.addView(imageView4);
                return jue;
            case 2:
                FrameLayout frameLayout3 = (FrameLayout) obj;
                k77[] k77Arr3 = RecordControlsWidget.m1;
                a4c a4c3 = new a4c(recordControlsWidget, 4);
                FrameLayout frameLayout4 = new FrameLayout(frameLayout3.getContext());
                frameLayout4.setId(y9a.c);
                FrameLayout.LayoutParams layoutParams9 = new FrameLayout.LayoutParams(-1, -1);
                layoutParams9.gravity = 17;
                frameLayout4.setLayoutParams(layoutParams9);
                a4c3.invoke(frameLayout4);
                frameLayout3.addView(frameLayout4);
                ImageView imageView5 = new ImageView(frameLayout3.getContext());
                imageView5.setId(y9a.a);
                float f8 = (float) 36;
                FrameLayout.LayoutParams layoutParams10 = new FrameLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f8), a24.X(f8 * dh4.c().getDisplayMetrics().density));
                layoutParams10.gravity = 17;
                imageView5.setLayoutParams(layoutParams10);
                me4.o((float) 4, dh4.c().getDisplayMetrics().density, imageView5);
                imageView5.setScaleType(ImageView.ScaleType.CENTER_INSIDE);
                imageView5.setImageDrawable(recordControlsWidget.D0());
                a24.a0(imageView5, new c4c(recordControlsWidget, 3));
                urd.B(new wua(recordControlsWidget, (Continuation) null, 8, false), imageView5);
                frameLayout3.addView(imageView5);
                return jue;
            case 3:
                LinearLayout linearLayout3 = (LinearLayout) obj;
                k77[] k77Arr4 = RecordControlsWidget.m1;
                a4c a4c4 = new a4c(recordControlsWidget, 6);
                FrameLayout frameLayout5 = new FrameLayout(linearLayout3.getContext());
                float f9 = (float) 28;
                frameLayout5.setLayoutParams(new LinearLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f9), a24.X(f9 * dh4.c().getDisplayMetrics().density)));
                a4c4.invoke(frameLayout5);
                linearLayout3.addView(frameLayout5);
                TextView textView2 = new TextView(linearLayout3.getContext());
                textView2.setId(y9a.k);
                LinearLayout.LayoutParams layoutParams11 = new LinearLayout.LayoutParams(-2, -2);
                layoutParams11.gravity = 16;
                layoutParams11.setMarginStart(a24.X(((float) 4) * dh4.c().getDisplayMetrics().density));
                textView2.setLayoutParams(layoutParams11);
                nte.k.b(textView2, yq4.b);
                urd.B(new c3(recordControlsWidget, (Continuation) null, 28), textView2);
                linearLayout3.addView(textView2);
                q60 q60 = new q60(linearLayout3.getContext());
                q60.setId(y9a.t);
                LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(a24.X(((float) 0) * dh4.c().getDisplayMetrics().density), a24.X(((float) 24) * dh4.c().getDisplayMetrics().density));
                layoutParams12.setMarginStart(a24.X(((float) 8) * dh4.c().getDisplayMetrics().density));
                layoutParams12.setMarginEnd(a24.X(((float) 2) * dh4.c().getDisplayMetrics().density));
                layoutParams12.weight = 1.0f;
                layoutParams12.gravity = 16;
                q60.setLayoutParams(layoutParams12);
                q60.setListener(new d4b(q60, 2, recordControlsWidget));
                linearLayout3.addView(q60);
                return jue;
            case 4:
                FrameLayout frameLayout6 = (FrameLayout) obj;
                k77[] k77Arr5 = RecordControlsWidget.m1;
                FrameLayout frameLayout7 = new FrameLayout(frameLayout6.getContext());
                frameLayout7.setId(y9a.b);
                float f10 = (float) 84;
                FrameLayout.LayoutParams layoutParams13 = new FrameLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f10), a24.X(dh4.c().getDisplayMetrics().density * f10));
                layoutParams13.gravity = 17;
                frameLayout7.setLayoutParams(layoutParams13);
                frameLayout7.setBackground((GradientDrawable) recordControlsWidget.T0.getValue());
                urd.B(new d4c(recordControlsWidget, (Continuation) null, 1), frameLayout7);
                frameLayout6.addView(frameLayout7);
                FrameLayout frameLayout8 = new FrameLayout(frameLayout6.getContext());
                FrameLayout.LayoutParams layoutParams14 = new FrameLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f10), a24.X(f10 * dh4.c().getDisplayMetrics().density));
                layoutParams14.gravity = 17;
                frameLayout8.setLayoutParams(layoutParams14);
                frameLayout8.setBackground((GradientDrawable) recordControlsWidget.U0.getValue());
                urd.B(new d4c(recordControlsWidget, (Continuation) null, 0), frameLayout8);
                frameLayout6.addView(frameLayout8);
                return jue;
            case 5:
                FrameLayout frameLayout9 = (FrameLayout) obj;
                k77[] k77Arr6 = RecordControlsWidget.m1;
                TextView textView3 = new TextView(frameLayout9.getContext());
                textView3.setId(y9a.g);
                FrameLayout.LayoutParams layoutParams15 = new FrameLayout.LayoutParams(-2, -1);
                layoutParams15.gravity = 17;
                textView3.setLayoutParams(layoutParams15);
                textView3.setGravity(17);
                textView3.setText(z9a.h);
                textView3.setCompoundDrawablesRelativeWithIntrinsicBounds((InsetDrawable) recordControlsWidget.S0.getValue(), (Drawable) null, (Drawable) null, (Drawable) null);
                nte.o.b(textView3, yq4.b);
                urd.B(new wua(recordControlsWidget, (Continuation) null, 9, false), textView3);
                frameLayout9.addView(textView3);
                return jue;
            default:
                FrameLayout frameLayout10 = (FrameLayout) obj;
                k77[] k77Arr7 = RecordControlsWidget.m1;
                View view2 = new View(frameLayout10.getContext());
                view2.setId(y9a.j);
                float f11 = (float) 8;
                FrameLayout.LayoutParams layoutParams16 = new FrameLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f11), a24.X(f11 * dh4.c().getDisplayMetrics().density));
                layoutParams16.gravity = 17;
                view2.setLayoutParams(layoutParams16);
                view2.setBackground((GradientDrawable) recordControlsWidget.W0.getValue());
                urd.B(new e4c(recordControlsWidget, (Continuation) null, 1), view2);
                frameLayout10.addView(view2);
                ImageView imageView6 = new ImageView(frameLayout10.getContext());
                imageView6.setId(y9a.n);
                float f12 = (float) 28;
                imageView6.setLayoutParams(new LinearLayout.LayoutParams(a24.X(dh4.c().getDisplayMetrics().density * f12), a24.X(f12 * dh4.c().getDisplayMetrics().density)));
                imageView6.setImageDrawable((Drawable) recordControlsWidget.O0.getValue());
                imageView6.setVisibility(8);
                urd.B(new e4c(recordControlsWidget, (Continuation) null, 2), imageView6);
                a24.a0(imageView6, new c4c(recordControlsWidget, 4));
                frameLayout10.addView(imageView6);
                return jue;
        }
    }
}
