package defpackage;

import java.util.LinkedHashMap;

/* renamed from: ky2  reason: default package */
public final class ky2 {
    public static final zo4 b = new zo4(16);
    public static final LinkedHashMap c = new LinkedHashMap();
    public static final ky2 d;
    public static final ky2 e;
    public static final ky2 f;
    public static final ky2 g;
    public static final ky2 h;
    public static final ky2 i;
    public static final ky2 j;
    public static final ky2 k;
    public static final ky2 l;
    public static final ky2 m;
    public static final ky2 n;
    public static final ky2 o;
    public static final ky2 p;
    public static final ky2 q;
    public static final ky2 r;
    public static final ky2 s;
    public static final gk9 t;
    public final String a;

    static {
        gk9 gk9 = new gk9(8);
        t = gk9;
        gk9.a(gk9, "SSL_RSA_WITH_NULL_MD5");
        gk9.a(gk9, "SSL_RSA_WITH_NULL_SHA");
        gk9.a(gk9, "SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        gk9.a(gk9, "SSL_RSA_WITH_RC4_128_MD5");
        gk9.a(gk9, "SSL_RSA_WITH_RC4_128_SHA");
        gk9.a(gk9, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        gk9.a(gk9, "SSL_RSA_WITH_DES_CBC_SHA");
        d = gk9.a(gk9, "SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        gk9.a(gk9, "SSL_DHE_DSS_WITH_DES_CBC_SHA");
        gk9.a(gk9, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        gk9.a(gk9, "SSL_DHE_RSA_WITH_DES_CBC_SHA");
        gk9.a(gk9, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        gk9.a(gk9, "SSL_DH_anon_WITH_RC4_128_MD5");
        gk9.a(gk9, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        gk9.a(gk9, "SSL_DH_anon_WITH_DES_CBC_SHA");
        gk9.a(gk9, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "TLS_KRB5_WITH_DES_CBC_SHA");
        gk9.a(gk9, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "TLS_KRB5_WITH_RC4_128_SHA");
        gk9.a(gk9, "TLS_KRB5_WITH_DES_CBC_MD5");
        gk9.a(gk9, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        gk9.a(gk9, "TLS_KRB5_WITH_RC4_128_MD5");
        gk9.a(gk9, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        gk9.a(gk9, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        gk9.a(gk9, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        gk9.a(gk9, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        e = gk9.a(gk9, "TLS_RSA_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_DH_anon_WITH_AES_128_CBC_SHA");
        f = gk9.a(gk9, "TLS_RSA_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_DH_anon_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_RSA_WITH_NULL_SHA256");
        gk9.a(gk9, "TLS_RSA_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_RSA_WITH_AES_256_CBC_SHA256");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        gk9.a(gk9, "TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        gk9.a(gk9, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        gk9.a(gk9, "TLS_PSK_WITH_RC4_128_SHA");
        gk9.a(gk9, "TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "TLS_PSK_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_PSK_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_RSA_WITH_SEED_CBC_SHA");
        g = gk9.a(gk9, "TLS_RSA_WITH_AES_128_GCM_SHA256");
        h = gk9.a(gk9, "TLS_RSA_WITH_AES_256_GCM_SHA384");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        gk9.a(gk9, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        gk9.a(gk9, "TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        gk9.a(gk9, "TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        gk9.a(gk9, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        gk9.a(gk9, "TLS_FALLBACK_SCSV");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_NULL_SHA");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_NULL_SHA");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_RC4_128_SHA");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_ECDHE_RSA_WITH_NULL_SHA");
        gk9.a(gk9, "TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        gk9.a(gk9, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        i = gk9.a(gk9, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        j = gk9.a(gk9, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_anon_WITH_NULL_SHA");
        gk9.a(gk9, "TLS_ECDH_anon_WITH_RC4_128_SHA");
        gk9.a(gk9, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        gk9.a(gk9, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        k = gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        l = gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        gk9.a(gk9, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        m = gk9.a(gk9, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        n = gk9.a(gk9, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        gk9.a(gk9, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        gk9.a(gk9, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        gk9.a(gk9, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        o = gk9.a(gk9, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        p = gk9.a(gk9, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        gk9.a(gk9, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        gk9.a(gk9, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        q = gk9.a(gk9, "TLS_AES_128_GCM_SHA256");
        r = gk9.a(gk9, "TLS_AES_256_GCM_SHA384");
        s = gk9.a(gk9, "TLS_CHACHA20_POLY1305_SHA256");
        gk9.a(gk9, "TLS_AES_128_CCM_SHA256");
        gk9.a(gk9, "TLS_AES_128_CCM_8_SHA256");
    }

    public ky2(String str) {
        this.a = str;
    }

    public final String toString() {
        return this.a;
    }
}
