package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* renamed from: we3  reason: default package */
public final class we3 {
    public int a;
    public final ze3 b;
    public final ye3 c;
    public final xe3 d;
    public final af3 e;
    public HashMap f = new HashMap();

    /* JADX WARNING: type inference failed for: r0v0, types: [ze3, java.lang.Object] */
    /* JADX WARNING: type inference failed for: r0v1, types: [ye3, java.lang.Object] */
    /* JADX WARNING: type inference failed for: r0v2, types: [xe3, java.lang.Object] */
    /* JADX WARNING: type inference failed for: r0v3, types: [java.lang.Object, af3] */
    public we3() {
        ? obj = new Object();
        obj.a = 0;
        obj.b = 0;
        obj.c = 1.0f;
        obj.d = Float.NaN;
        this.b = obj;
        ? obj2 = new Object();
        obj2.a = -1;
        obj2.b = 0;
        obj2.c = -1;
        obj2.d = Float.NaN;
        obj2.e = Float.NaN;
        obj2.f = Float.NaN;
        obj2.g = -1;
        obj2.h = null;
        obj2.i = -1;
        this.c = obj2;
        ? obj3 = new Object();
        obj3.a = false;
        obj3.d = -1;
        obj3.e = -1;
        obj3.f = -1.0f;
        obj3.g = true;
        obj3.h = -1;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = -1;
        obj3.u = -1;
        obj3.v = -1;
        obj3.w = 0.5f;
        obj3.x = 0.5f;
        obj3.y = null;
        obj3.z = -1;
        obj3.A = 0;
        obj3.B = 0.0f;
        obj3.C = -1;
        obj3.D = -1;
        obj3.E = -1;
        obj3.F = 0;
        obj3.G = 0;
        obj3.H = 0;
        obj3.I = 0;
        obj3.J = 0;
        obj3.K = 0;
        obj3.L = 0;
        obj3.M = Integer.MIN_VALUE;
        obj3.N = Integer.MIN_VALUE;
        obj3.O = Integer.MIN_VALUE;
        obj3.P = Integer.MIN_VALUE;
        obj3.Q = Integer.MIN_VALUE;
        obj3.R = Integer.MIN_VALUE;
        obj3.S = Integer.MIN_VALUE;
        obj3.T = -1.0f;
        obj3.U = -1.0f;
        obj3.V = 0;
        obj3.W = 0;
        obj3.X = 0;
        obj3.Y = 0;
        obj3.Z = 0;
        obj3.a0 = 0;
        obj3.b0 = 0;
        obj3.c0 = 0;
        obj3.d0 = 1.0f;
        obj3.e0 = 1.0f;
        obj3.f0 = -1;
        obj3.g0 = 0;
        obj3.h0 = -1;
        obj3.l0 = false;
        obj3.m0 = false;
        obj3.n0 = true;
        obj3.o0 = 0;
        this.d = obj3;
        ? obj4 = new Object();
        obj4.a = 0.0f;
        obj4.b = 0.0f;
        obj4.c = 0.0f;
        obj4.d = 1.0f;
        obj4.e = 1.0f;
        obj4.f = Float.NaN;
        obj4.g = Float.NaN;
        obj4.h = -1;
        obj4.i = 0.0f;
        obj4.j = 0.0f;
        obj4.k = 0.0f;
        obj4.l = false;
        obj4.m = 0.0f;
        this.e = obj4;
    }

    public final void a(re3 re3) {
        xe3 xe3 = this.d;
        re3.e = xe3.h;
        re3.f = xe3.i;
        re3.g = xe3.j;
        re3.h = xe3.k;
        re3.i = xe3.l;
        re3.j = xe3.m;
        re3.k = xe3.n;
        re3.l = xe3.o;
        re3.m = xe3.p;
        re3.n = xe3.q;
        re3.o = xe3.r;
        re3.s = xe3.s;
        re3.t = xe3.t;
        re3.u = xe3.u;
        re3.v = xe3.v;
        re3.leftMargin = xe3.F;
        re3.rightMargin = xe3.G;
        re3.topMargin = xe3.H;
        re3.bottomMargin = xe3.I;
        re3.A = xe3.R;
        re3.B = xe3.Q;
        re3.x = xe3.N;
        re3.z = xe3.P;
        re3.E = xe3.w;
        re3.F = xe3.x;
        re3.p = xe3.z;
        re3.q = xe3.A;
        re3.r = xe3.B;
        re3.G = xe3.y;
        re3.T = xe3.C;
        re3.U = xe3.D;
        re3.I = xe3.T;
        re3.H = xe3.U;
        re3.K = xe3.W;
        re3.J = xe3.V;
        re3.W = xe3.l0;
        re3.X = xe3.m0;
        re3.L = xe3.X;
        re3.M = xe3.Y;
        re3.P = xe3.Z;
        re3.Q = xe3.a0;
        re3.N = xe3.b0;
        re3.O = xe3.c0;
        re3.R = xe3.d0;
        re3.S = xe3.e0;
        re3.V = xe3.E;
        re3.c = xe3.f;
        re3.a = xe3.d;
        re3.b = xe3.e;
        re3.width = xe3.b;
        re3.height = xe3.c;
        String str = xe3.k0;
        if (str != null) {
            re3.Y = str;
        }
        re3.Z = xe3.o0;
        re3.setMarginStart(xe3.K);
        re3.setMarginEnd(xe3.J);
        re3.a();
    }

    public final Object clone() {
        we3 we3 = new we3();
        xe3 xe3 = we3.d;
        xe3.getClass();
        xe3 xe32 = this.d;
        xe3.a = xe32.a;
        xe3.b = xe32.b;
        xe3.c = xe32.c;
        xe3.d = xe32.d;
        xe3.e = xe32.e;
        xe3.f = xe32.f;
        xe3.g = xe32.g;
        xe3.h = xe32.h;
        xe3.i = xe32.i;
        xe3.j = xe32.j;
        xe3.k = xe32.k;
        xe3.l = xe32.l;
        xe3.m = xe32.m;
        xe3.n = xe32.n;
        xe3.o = xe32.o;
        xe3.p = xe32.p;
        xe3.q = xe32.q;
        xe3.r = xe32.r;
        xe3.s = xe32.s;
        xe3.t = xe32.t;
        xe3.u = xe32.u;
        xe3.v = xe32.v;
        xe3.w = xe32.w;
        xe3.x = xe32.x;
        xe3.y = xe32.y;
        xe3.z = xe32.z;
        xe3.A = xe32.A;
        xe3.B = xe32.B;
        xe3.C = xe32.C;
        xe3.D = xe32.D;
        xe3.E = xe32.E;
        xe3.F = xe32.F;
        xe3.G = xe32.G;
        xe3.H = xe32.H;
        xe3.I = xe32.I;
        xe3.J = xe32.J;
        xe3.K = xe32.K;
        xe3.L = xe32.L;
        xe3.M = xe32.M;
        xe3.N = xe32.N;
        xe3.O = xe32.O;
        xe3.P = xe32.P;
        xe3.Q = xe32.Q;
        xe3.R = xe32.R;
        xe3.S = xe32.S;
        xe3.T = xe32.T;
        xe3.U = xe32.U;
        xe3.V = xe32.V;
        xe3.W = xe32.W;
        xe3.X = xe32.X;
        xe3.Y = xe32.Y;
        xe3.Z = xe32.Z;
        xe3.a0 = xe32.a0;
        xe3.b0 = xe32.b0;
        xe3.c0 = xe32.c0;
        xe3.d0 = xe32.d0;
        xe3.e0 = xe32.e0;
        xe3.f0 = xe32.f0;
        xe3.g0 = xe32.g0;
        xe3.h0 = xe32.h0;
        xe3.k0 = xe32.k0;
        int[] iArr = xe32.i0;
        if (iArr == null || xe32.j0 != null) {
            xe3.i0 = null;
        } else {
            xe3.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        xe3.j0 = xe32.j0;
        xe3.l0 = xe32.l0;
        xe3.m0 = xe32.m0;
        xe3.n0 = xe32.n0;
        xe3.o0 = xe32.o0;
        ye3 ye3 = we3.c;
        ye3.getClass();
        ye3 ye32 = this.c;
        ye32.getClass();
        ye3.a = ye32.a;
        ye3.c = ye32.c;
        ye3.e = ye32.e;
        ye3.d = ye32.d;
        ze3 ze3 = we3.b;
        ze3.getClass();
        ze3 ze32 = this.b;
        ze32.getClass();
        ze3.a = ze32.a;
        ze3.c = ze32.c;
        ze3.d = ze32.d;
        ze3.b = ze32.b;
        af3 af3 = we3.e;
        af3.getClass();
        af3 af32 = this.e;
        af32.getClass();
        af3.a = af32.a;
        af3.b = af32.b;
        af3.c = af32.c;
        af3.d = af32.d;
        af3.e = af32.e;
        af3.f = af32.f;
        af3.g = af32.g;
        af3.h = af32.h;
        af3.i = af32.i;
        af3.j = af32.j;
        af3.k = af32.k;
        af3.l = af32.l;
        af3.m = af32.m;
        we3.a = this.a;
        return we3;
    }
}
